### ISSUE TITLE
HTTPS required

### ISSUE THREAD

**Issue by ndorfin** [nzruby/conf#28]
Hi nzruby,

I'm working on a fork that'll add ServiceWorkers, but these ServiceWorkers won't work if the site is not served over SSL/TLS.
Who can I get in contact with to organise this certificate? Or can someone please take a look at getting a free certificate through [LetsEncrypt.org](https://letsencrypt.org/)?

Thanks!
-Shaun

**Comment by ndorfin** [comment]
Friendly paging @mermop :)

**Comment by mermop** [comment]
Oh hello! @steveh is the person who knows about these things

**Comment by steveh** [comment]
We don't have a web server so don't really have any way to install a certificate. I'll look at introducing cloudflare.

**Comment by ndorfin** [comment]
Hi @steveh - ~~it might be as simple as [enabling HTTPS for Github Pages](https://help.github.com/articles/securing-your-github-pages-site-with-https/) but a CDN would be even better - gh-pages could serve as a staging server.~~
Drat, no support for custom domains.

**Comment by steveh** [comment]
Done!

**Comment by ndorfin** [comment]
Thanks @steveh!

Would you mind enabling '[Always use HTTPS](https://support.cloudflare.com/hc/en-us/articles/200170536-How-do-I-redirect-all-visitors-to-HTTPS-SSL-)' - that way visitors to the existing URL will be redirected to the HTTPS equivalent.

@mermop Any links you use to the site should have the HTTPS included now - no redirects for the greater good! :)

**Comment by steveh** [comment]
Cool - enabled

**Comment by mermop** [comment]
Thanks @steveh
