### ISSUE TITLE
Google Maps loading alternatives?

### ISSUE THREAD

**Issue by ndorfin** [nzruby/conf#36]
Would it be possible to consider alternatives for the Google Maps instance on the homepage, please? The reason I'm pushing for an alternative, is that come ServiceWorkers, we want something we can cache. A static image would be great to cache.

We could:

- Link to a venue page.
- Replace the inline Google Maps instance with a stylised map.
- Replace the inline Google Maps instance with a Google Static Maps image. 
- Look at lazy-loading the inline map using the new [IntersectionObserver](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API), or at least delaying the load till last.

Having a static image with a link to a Google Maps URI would mean a handset would open the Google Maps app if it was installed.

What do you think @mermop?

**Comment by mermop** [comment]
Google Static Maps with a Google Maps URI should work - I haven't used that API before, are you familiar with it?

**Comment by ndorfin** [comment]
@mermop Yup, you set the image's `src` attribute to a URL to the Google Static Maps host, and it generates a PNG for you based on the coordinates, width, height, and other queryString params.

**Comment by mermop** [comment]
Sounds good to me. The google maps plugin also keeps annoying me when I scroll down the page because it captures your scroll, so I'm happy to kill it

**Comment by ndorfin** [comment]
@mermop I've got a PR ready for this.
It's currently set up to not use a Google Maps API key. The site will [need a free API key](https://developers.google.com/maps/documentation/static-maps/get-api-key), which [allows for 25,000 requests a day](https://developers.google.com/maps/documentation/static-maps/usage-limits)
