### ISSUE TITLE
Remove the duplicate main menu

### ISSUE THREAD

**Issue by ndorfin** [nzruby/conf#37]
Hi! 👋 

The main menu is repeated, once for mobile, the second for larger screens.
With some breakpoint-related CSS, we can shift one menu from mobile mode to tablet mode pretty easily.

If you're happy with that plan, I'll look at doing the required changes in a PR.

-S

**Comment by mermop** [comment]
I wouldn't prioritise this over the other performance improvements you've highlighted but if this is a thing you want to do I'm not gonna stop you ✨
