### ISSUE TITLE
Webfont audit

### ISSUE THREAD

**Issue by ndorfin** [nzruby/conf#38]
Hi! 👋 

I thought the use of webfonts on the site was a little out of control, so I did an audit and found the following:

1. It looks like `Work Sans` is being used for most of the site: >99%
2. `Source Code Pro` is intended to be used for sponsors names in the sponsors partial, if the `sponsor.show_name` boolean is true. But none of the sponsors are represented as such.
3. `Source Sans Pro` is only used once in the `.hero_date` element on the homepage. This could be replaced with a suitable cross-browser font, saving us 2 blocking HTTP requests and ~15KB.
4. `YoungSerif` and `OleoSwash` are declared, imported, make 1 blocking request each, but are never used.

Recommendations:

1. Leave `Work Sans` as is.
2. Remove `Source Code Pro`
3. Replace `Source Sans Pro` with something like `Droid Sans` or `sans-serif`
4. Remove `YoungSerif` and `OleoSwash`

Next steps:

We could see a healthy improvement in rendering performance if we remove these fonts. I'm happy to do the work with your blessing :)

-S

**Comment by mermop** [comment]
We were initially using Young Serif and Oleo Swash but they were replaced in #22. The `.hero_date` element should probably be Work Sans now - then we can remove the other 4.

**Comment by mermop** [comment]
Turns out Oleo Swash is still being used, it's the logotype font, it's only used once now so there could be some argument for replacing that one use with a SVG but I'm not too bothered
