### ISSUE TITLE
Fingerprint assets

### ISSUE THREAD

**Issue by mermop** [nzruby/conf#45]
We should fingerprint assets (index.css and index.js in particular) to prevent overzealous caching messing with deploys

**Comment by ndorfin** [comment]
This will be particularly useful for when we create Service Worker caches.

It could be as easy as enabling asset hashing in Middleman.

There are some files we don't want to asset-hash, such as:

```
opengraph.png
*touch-icon*.*
service-worker.js
*.xml
*.txt
*.json
favicon.ico
```

These files should be listed in middleman's asset-hash's `ignore` param.

We'll still need a separate task to set up CloudFlare invalidation in `config.rb`
