### ISSUE TITLE
Set up Caching policies

### ISSUE THREAD

**Issue by ndorfin** [nzruby/conf#51]
During a build and deployment, we should set the following caching policies in `config.rb`

Asset Cache-Control, max-age = years
HTML Cache Control for HTML: max-age 5 minutes
Individual Cache Control: `service-worker.js` max-age: 0, must revalidate.

**Comment by mermop** [comment]
Can we do that with gh-pages?

**Comment by ndorfin** [comment]
Doesn't look like it :(
Looks like we'd have to manage it through CloudFlare. The most critical change we'd need is to not cache the Service Worker. That can be done through [CloudFlare's Page Rules](https://support.cloudflare.com/hc/en-us/articles/202775670-How-Do-I-Tell-Cloudflare-What-to-Cache-)

**Comment by mermop** [comment]
As per #57 - service worker is not cached now - not too much else we can do
